# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# DBTITLE 1,Cell 2
# MAGIC %md
# MAGIC **Note:** This notebook is configured to run on a SQL warehouse, which only supports SQL cells. For Python analysis, switch to a compute cluster.

# COMMAND ----------

# MAGIC %sql
# MAGIC -- !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.
# MAGIC
# MAGIC USE CATALOG `ecom`;
# MAGIC USE SCHEMA `bronze`;
# MAGIC

# COMMAND ----------

# DBTITLE 1,Cell 4
# MAGIC %sql
# MAGIC SELECT * FROM ecom.bronze.orders_bronze LIMIT 10

# COMMAND ----------

df = spark.read.table("ecom.bronze.orders_bronze")
display(df.limit(40))

# COMMAND ----------

df.printSchema()

# COMMAND ----------

df.count()

# COMMAND ----------

from pyspark.sql.functions import col, sum, when

display(
    df.select([
        sum(col(c).isNull().cast('int')).alias(c)
        for c in df.columns
    ])
)

# COMMAND ----------

string_cols = [c for c, t in df.dtypes if t == "string"]
print(string_cols)

# COMMAND ----------

display(df.select([
    sum(when(col(c) == "-", 1).otherwise(0)).alias(c)
    for c in string_cols
]))

# COMMAND ----------

df.printSchema()

# COMMAND ----------

from pyspark.sql import functions as F

# COMMAND ----------

# DBTITLE 1,Cell 14
df.filter(F.col("customer_id").isNotNull()).limit(1).count() > 0

# COMMAND ----------

df.filter(F.col("age").isNotNull()).limit(1).count() > 0

# COMMAND ----------

# select appr columns
total_rows = df.count()

# get cols which are not fully null
threshold = 0.1 * total_rows  # keep columns with at least 10% data

valid_cols = [
    c for c in df.columns
    if df.filter(F.col(c).isNotNull()).count() > threshold
]

df = df.select(valid_cols)

# COMMAND ----------

df.printSchema()

# COMMAND ----------

df = df.drop(
    "order_year",
    "order_month",
    "order_day",
    "order_hour",
    "order_minute",
    "order_second"
)

# COMMAND ----------

df.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Categorical Columns
# MAGIC - order_status
# MAGIC - order_priority
# MAGIC - coupon_used
# MAGIC - is_weekend
# MAGIC - campaign_source

# COMMAND ----------

df.select(["order_status", 'order_priority', 'coupon_used', 'is_weekend', 'campaign_source']).show(40)

# COMMAND ----------

df.select("order_status").distinct().show()

# COMMAND ----------

# MAGIC %md
# MAGIC #### Standardize *order_status*
# MAGIC - lowercase
# MAGIC - trimmed (no spaces)

# COMMAND ----------

df = df.withColumn(
    "order_status",
    F.trim(F.lower(F.col("order_status")))
)

# COMMAND ----------

df.select("order_status").distinct().show()

# COMMAND ----------

df.select("order_priority").distinct().show()

# COMMAND ----------

# standardized this also
df = df.withColumn(
    "order_priority",
    F.trim(F.lower(F.col("order_priority")))
)

# COMMAND ----------

df.select("order_priority").distinct().show()

# COMMAND ----------

df.select("is_weekend").distinct().show()

# COMMAND ----------

# standardized this also
df = df.withColumn(
    "is_weekend",
    F.trim(F.lower(F.col("is_weekend")))
)

# COMMAND ----------

df.select("is_weekend").distinct().show()

# COMMAND ----------

df.select("coupon_used").distinct().show()

# COMMAND ----------

# standardized this also
df = df.withColumn(
    "coupon_used",
    F.trim(F.lower(F.col("coupon_used")))
)

# COMMAND ----------

df.select("coupon_used").distinct().show()

# COMMAND ----------

df = df.withColumn(
    "coupon_used",
    F.when(F.col("coupon_used") == "yes", 1).otherwise(0)
).withColumn(
    "is_weekend",
    F.when(F.col("is_weekend") == "yes", 1).otherwise(0)
)

# COMMAND ----------

df.printSchema()

# COMMAND ----------

df.select("campaign_source").distinct().show()

# COMMAND ----------

# standardized this also
df = df.withColumn(
    "campaign_source",
    F.trim(F.lower(F.col("campaign_source")))
)

# COMMAND ----------

df.select("campaign_source").distinct().show()

# COMMAND ----------

df.select(["order_status", 'order_priority', 'coupon_used', 'is_weekend', 'campaign_source']).distinct().show()

# COMMAND ----------

df.select("is_weekend").distinct().show()

# COMMAND ----------

# MAGIC %md
# MAGIC ### If coupon_used = 0 then force coupon_code = NULL

# COMMAND ----------

# coupon_used = 0 but coupon_code exists 

display(df.filter(
    (F.col("coupon_used") == 0) & 
    (F.col("coupon_code").isNotNull())
))

# COMMAND ----------

# coupon_used = 1 but coupon_code is NULL ❌

display(df.filter(
    (F.col("coupon_used") == 1) & 
    (F.col("coupon_code").isNull())
))

# COMMAND ----------

df = df.withColumn(
    "coupon_code",
    F.when(F.col("coupon_used") == 0, None)
     .otherwise(F.col("coupon_code"))
)

# COMMAND ----------

display(df.filter((F.col("coupon_used") == 0) & (F.col("coupon_code").isNotNull())))

# COMMAND ----------

df = df.drop("_source_file")

# COMMAND ----------

display(df.limit(50))

# COMMAND ----------

df.groupBy("order_id").count().filter("count > 1").show()

# COMMAND ----------

display(df.filter(F.col("order_id") == "ORD-FL914"))

# COMMAND ----------

df = df.withColumn(
    "order_key",
    F.concat_ws("_", F.col("order_id"), F.col("order_date"))
)

# COMMAND ----------

df.groupBy("order_key").count().filter("count > 1").show()

# COMMAND ----------

# MAGIC %md
# MAGIC ### check nulls

# COMMAND ----------

df.filter(F.col("order_id").isNull()).count()

# COMMAND ----------

df.filter(F.col("customer_id").isNull()).count()


# COMMAND ----------

df.filter(F.col("order_date").isNull()).count()

# COMMAND ----------

df = df.select(
    "order_key",
    "order_id",
    "customer_id",
    "country",
    "city",
    "order_date",
    "order_status",
    "order_priority",
    "currency",
    "coupon_used",
    "coupon_code",
    "campaign_source",
    "_ingestion_timestamp"
)

# COMMAND ----------

display(df.limit(50))

# COMMAND ----------

